[tool.ruff]
line-length = 500
target-version = "py312"

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
line-ending = "auto"

[tool.ruff.lint]
fixable = ["ALL"]
select = ["E", "F", "I"]
ignore = []

[tool.isort]
profile = "black"
line_length = 500
indent = "\t"
